### ISSUE TITLE
Strict parsing mode for objects

### ISSUE THREAD

**Issue by enlait** [tethys-json/tethys#38]
I want to accept a patch request model with optional fields, and return an error, if there are unknown fields that are normally ignored by parser.

For example, I have a user and user patch models:
```
case class User(id: UUID, name: String, phone: String, email: String)

case class UserPatch(name: Option[String], phone: Option[String], email: Option[String])
```
and I want a patch request with body like that fail:
```
{
  "name": "Ivan",
  "age": 42
}
```

preferably with an error, indicating which field is unwanted.

**Comment by eld0727** [comment]
Thanks for this feature request. 
You can see new syntax in tests:  [JsonReaderBuilder](https://github.com/tethys-json/tethys/commit/60f37b3f73dc88368707e0fe439df36f5ea8bb56#diff-54c2dd80c5ee7d7bfa8a21da5033bbbfR86) and [ReaderDerivation](https://github.com/tethys-json/tethys/commit/60f37b3f73dc88368707e0fe439df36f5ea8bb56#diff-78d5a7f59de20aa3b8081f58d18a8c37)
