### ISSUE TITLE
not found: value ReaderError

### ISSUE THREAD

**Issue by k-bespalov** [tethys-json/tethys#41]
Hello!

I've tried to use camelCase <-> snake_case wrapper FieldStyle.lowerSnakecase

```
case class QuestionCount(totalCount: Int, activeCount: Int)

implicit val questionCountResponseFormat: JsonReader[Response.QuestionCount] = jsonReader[Response.QuestionCount](
    ReaderDerivationConfig.withFieldStyle(FieldStyle.lowerSnakecase).strict
)
```

I get error
`
Error:(77, 116) not found: value ReaderError
  implicit val questionCountResponseFormat: JsonReader[Response.QuestionCount] = jsonReader[Response.QuestionCount](
`
and not only in this case, also in similar places of code.

The error goes out  when I import `import tethys.readers.ReaderError`, but it's a little bit strange because ReaderError class is not even some kind of implicits.

**Comment by eld0727** [comment]
Hello!
Thanks for your issue. It is published under v0.8.0.1 and ready to use
