### ISSUE TITLE
Denial of service when parsing too long JSON numbers as double or float

### ISSUE THREAD

**Issue by eld0727** [tethys-json/tethys#43]
Sub-quadratic decreasing of throughput when length of the JSON number to parse is increasing.

On contemporary CPUs parsing of such JSON numbers that are bound on doubles or floats and has 1000000 decimal digits (~1Mb) can took more than 14 seconds.

**Comment by REDNBLACK** [comment]
@eld0727 Related https://github.com/circe/circe/issues/1363

**Comment by eld0727** [comment]
No, it's about parsing Double, Long or any Number and not just BigDecimal. I think that BigDecimal values are out of the scope of this issue

**Comment by eld0727** [comment]
Can't represent anymore
