### ISSUE TITLE
Add ability to enable pretty printing when rendering

### ISSUE THREAD

**Issue by scf37** [tethys-json/tethys#53]
Reason:

Many public APIs support json pretty printing for easier debugging:

`GET /api/v1/pets?pretty`

**Comment by eld0727** [comment]
@scf37, i think you can use `tethys.jackson.preatty._`

**Comment by scf37** [comment]
I do not think it will work per request. Of course, I can create two different `JsonWriter`-s per case class (one for compact json and another for pretty json) and select correct one dynamically but that's ugly.

**Comment by eld0727** [comment]
No, you just need to pass correct TokenWriter to your route serializer

**Comment by scf37** [comment]
Oh, you are right.
