### ISSUE TITLE
Simplify creating JsonWriter for ADT with dicriminator field

### ISSUE THREAD

**Issue by LMnet** [tethys-json/tethys#66]
https://scastie.scala-lang.org/LMnet/lzx3x28BSCifSyjZABiHQQ

The code for `fooBarWriter` from the snippet above is pretty low-level and imperative. It would be cool to have a DSL for simplifying this case.

**Comment by REDNBLACK** [comment]
Implemented in https://github.com/tethys-json/tethys/pull/142, released with v0.26.0
